const WORDS = [
"aback","abase","abate","abbey","abbot","abort","about","above","abuse","abyss",
"actor","acute","adage","adapt","adept","admin","admit","adobe","adopt","adult",
"after","again","agent","agile","aging","agony","agree","ahead","aisle","alarm",
"album","alert","algae","alias","alibi","alien","align","alike","alive","allow",
"alone","along","aloof","alter","amber","amend","amiss","among","ample","amuse",
"angel","anger","angle","angry","anime","ankle","annex","annoy","antic","anvil",
"aorta","apart","apple","apply","apron","arena","argue","arise","armor","aroma",
"array","arrow","aside","asset","atlas","audio","audit","avoid","await","awake",
"award","aware","awful","bacon","badge","badly","baker","baler","basic","basil",
"beach","beady","beard","beast","begin","being","belly","below","bench","berry",
"birth","black","blade","blame","blank","blast","blend","bless","blind","blink",
"block","blood","bloom","blown","blush","board","boast","bonus","boost","booth",
"brain","brake","brand","brave","bread","break","brick","bride","bring","broad",
"brown","brush","build","burst","cabin","cable","camel","candy","canny","cargo",
"carry","carve","catch","cause","chain","chair","chalk","champ","chant","chaos",
"charm","chart","chase","cheap","check","cheer","chess","chest","chief","child",
"chill","china","choir","choke","cigar","claim","class","clean","clear","clerk",
"click","cliff","climb","clock","close","cloth","cloud","coach","coast","color",
"could","count","court","cover","craft","crane","crash","cream","creed","crime",
"cross","crowd","crown","crude","crush","curve","cycle","daily","dairy","dance",
"death","debug","delay","delta","depth","dirty","dodge","donut","doubt","dozen",
"draft","drama","drawn","dream","dress","drift","drink","drive","drown","eager",
"early","earth","easel","elder","elect","elite","empty","enemy","enjoy","enter",
"equal","equip","error","essay","ethic","evade","event","exact","exist","extra",
"faith","false","fancy","fatal","fault","feast","fence","fever","field","fiery",
"fight","final","first","flame","flash","fleet","flesh","float","flood","floor",
"fluid","focus","force","forum","found","frame","fresh","front","frost","fruit",
"giant","glide","globe","grace","grade","grain","grant","grape","graph","grasp",
"green","grind","group","guard","guess","guest","guide","habit","happy","harsh",
"heart","heavy","honey","honor","horse","hotel","house","human","humor","ideal",
"image","index","inner","input","issue","ivory","jelly","joint","judge","juice",
"knife","knock","label","labor","layer","learn","leave","lemon","level","light",
"limit","local","logic","loose","lucky","lunch","magic","major","maker","march",
"match","maybe","medal","metal","meter","might","minor","model","money","month",
"moral","motor","mount","mouse","mouth","movie","music","naive","nerve","never",
"night","noise","north","novel","nurse","occur","ocean","offer","often","onion",
"order","other","outer","owner","panel","panic","paper","party","peace","phase",
"phone","photo","piece","pilot","pitch","place","plain","plane","plant","plate",
"point","power","press","price","pride","prime","print","prior","prize","proof",
"proud","queen","quick","quiet","radio","raise","range","rapid","ratio","reach",
"react","ready","realm","rebel","refer","relax","renew","reply","right","rival",
"river","rough","round","route","royal","rugby","rural","scale","scene","scope",
"score","sense","serve","seven","shade","shake","shall","shape","share","sharp",
"sheet","shelf","shell","shift","shine","shirt","shock","shoot","shore","short",
"sight","since","skill","sleep","slice","slide","slope","small","smart","smile",
"smoke","solid","solve","sorry","sound","south","space","spare","speak","speed",
"spend","spice","spike","spine","spite","split","sport","staff","stage","stand",
"start","state","steam","steel","stick","still","stock","stone","storm","story",
"strip","study","stuff","style","sugar","super","sweet","table","taste","teach",
"thank","their","theme","there","thick","thing","think","third","those","throw",
"tight","timer","tired","title","today","topic","total","touch","tower","toxic",
"trace","track","trade","train","treat","trend","trial","trust","truth","twice",
"uncle","under","union","unity","until","upper","upset","urban","usage","usual",
"value","video","virus","visit","vital","vivid","voice","waste","watch","water",
"weigh","whale","wheat","wheel","where","which","while","white","whole","woman",
"world","worry","worth","write","wrong","yield","young","youth"
];

WORDS.push(
"about","above","after","apple","award","basic","below","brown","chair","child",
"class","color","court","cover","death","early","error","event","faith","force",
"frame","front","fruit","ghost","grace","grade","grand","grass","green","guide",
"hotel","house","index","joint","judge","knife","known","label","laugh","layer",
"level","magic","major","match","metal","model","motor","movie","north","ocean",
"offer","owner","panel","phase","piece","pilot","pitch","plain","plane","plate",
"price","pride","print","prize","queen","radio","range","river","rough","royal",
"rural","scale","scene","scope","sheet","shell","shirt","shock","shoot","shore",
"sight","skill","sleep","slice","smile","smoke","solid","solve","sorry","speak",
"spend","spice","split","sport","staff","stage","steam","steel","stone","storm",
"style","sugar","sweet","table","theme","thick","thing","throw","tight","title",
"tower","trace","track","trade","treat","trial","trust","truth","twice","uncle",
"union","unity","upper","usual","visit","vital","waste","watch","wheel","worth",
"yield","youth"
);

WORDS.push(
"abhor","abide","abled","abode","abram","abuts","ached","aches","acids","acorn",
"acres","acted","actin","acton","added","adder","addle","adele","adieu","adore",
"adorn","adult","aegis","aerie","affix","afire","afoot","afoul","again","agape",
"agate","agent","aglow","agone","agony","agree","ahead","aided","aides","aimed",
"aisle","alarm","album","alder","aleph","alert","alfal","align","alike","alive",
"allay","alley","allot","allow","alloy","aloft","alone","along","aloof","alter",
"amaze","amber","amend","amiss","among","ample","amply","amuse","angel","anger",
"angle","angry","anime","ankle","annex","annoy","antic","anvil","aorta","apart",
"apple","apply","apron","arena","argue","arise","armed","armor","aroma","array",
"arrow","ashen","aside","asked","asset","atlas","atoll","atoms","audio","audit",
"avail","avert","avoid","await","awake","award","aware","awful","axial","axiom",
"azure","bacon","badge","badly","bagel","baked","baker","balls","banns","barge",
"basic","basil","beach","beads","beady","beard","beast","beats","began","begin",
"begun","being","belch","belly","below","bench","bends","berth","berry","birth",
"black","blade","blame","blank","blast","blend","bless","blind","blink","block",
"blood","bloom","blown","blues","bluff","board","boast","bonus","boost","booth",
"borne","bound","brain","brake","brand","brave","bread","break","brick","bride",
"bring","broad","broke","brown","brush","build","built","burst","buyer","cabin",
"cable","camel","canal","candy","canny","canoe","cargo","carry","carve","catch",
"cause","chain","chair","chalk","champ","chant","chaos","charm","chart","chase",
"cheap","check","cheek","cheer","chess","chest","chief","child","chill","china",
"choir","choke","chord","cigar","cinch","claim","clash","class","clean","clear",
"clerk","click","cliff","climb","cling","clock","close","cloth","cloud","coach",
"coast","colon","color","comic","could","count","court","cover","craft","crane",
"crash","cream","creed","crime","cross","crowd","crown","crude","cruel","crush",
"curve","cycle","daily","dairy","dance","dated","death","debut","debug","delay",
"delta","depth","dirty","dodge","doing","donut","doubt","dozen","draft","drain",
"drama","drawn","dream","dress","drift","drink","drive","drown","eager","early",
"earth","easel","edged","elder","elect","elite","empty","enemy","enjoy","enter",
"equal","equip","error","essay","ethic","evade","event","exact","exist","extra",
"faith","false","fancy","fatal","fault","feast","fence","fever","field","fiery",
"fight","final","first","flame","flash","fleet","flesh","float","flood","floor",
"fluid","focus","force","forum","found","frame","fresh","front","frost","fruit",
"giant","glide","globe","grace","grade","grain","grant","grape","graph","grasp",
"green","grind","group","guard","guess","guest","guide","habit","happy","harsh",
"heart","heavy","honey","honor","horse","hotel","house","human","humor","ideal",
"image","index","inner","input","issue","ivory","jelly","joint","judge","juice",
"knife","knock","label","labor","layer","learn","leave","lemon","level","light",
"limit","local","logic","loose","lucky","lunch","magic","major","maker","march",
"match","maybe","medal","metal","meter","might","minor","model","money","month",
"moral","motor","mount","mouse","mouth","movie","music","naive","nerve","never",
"night","noise","north","novel","nurse","occur","ocean","offer","often","onion",
"order","other","outer","owner","panel","panic","paper","party","peace","phase",
"phone","photo","piece","pilot","pitch","place","plain","plane","plant","plate",
"point","power","press","price","pride","prime","print","prior","prize","proof",
"proud","queen","quick","quiet","radio","raise","range","rapid","ratio","reach",
"react","ready","realm","rebel","refer","relax","renew","reply","right","rival",
"river","rough","round","route","royal","rugby","rural","scale","scene","scope",
"score","sense","serve","seven","shade","shake","shall","shape","share","sharp"
);


WORDS.push(
"abash","abets","abide","abler","abode","abuse","ached","aches","acids","acmes",
"acorn","acres","actor","acute","adage","adapt","added","addle","adept","adieu",
"adore","adorn","aegis","aerie","affix","afire","afoot","afoul","agape","agate",
"agave","agent","agile","aging","aglow","agony","agree","ahead","aisle","alamo",
"alarm","album","alder","alert","algae","alias","alibi","alien","align","alike",
"alive","allay","alley","allot","allow","alloy","aloft","alone","along","aloof",
"alter","amber","amend","amiss","among","ample","amply","amuse","angel","anger",
"angle","angry","ankle","annex","annoy","antic","anvil","aorta","apart","aphid",
"apple","apply","apron","arena","argue","arise","armed","armor","aroma","array",
"arrow","ashen","aside","asset","atlas","atoll","attic","audio","audit","avail",
"avert","avoid","await","awake","award","aware","awful","axial","axiom","azure",
"bacon","badge","badly","bagel","baked","baker","baler","balls","banal","bands",
"banjo","barge","basil","beach","beads","beady","beard","beast","beats","began",
"begin","begun","being","belch","belly","below","bench","berth","berry","birth",
"black","blade","blame","blank","blast","blend","bless","blind","blink","block",
"blood","bloom","blown","blues","bluff","board","boast","bonus","boost","booth",
"borne","bound","brain","brake","brand","brave","bread","break","brick","bride",
"bring","broad","broke","brown","brush","build","built","burst","buyer","cabin",
"cable","camel","canal","candy","canny","canoe","cargo","carry","carve","catch",
"cause","chain","chair","chalk","champ","chant","chaos","charm","chart","chase",
"cheap","check","cheek","cheer","chess","chest","chief","child","chill","china",
"choir","choke","chord","cigar","cinch","claim","clash","class","clean","clear",
"clerk","click","cliff","climb","cling","clock","close","cloth","cloud","coach",
"coast","colon","color","comic","could","count","court","cover","craft","crane",
"crash","cream","creed","crime","cross","crowd","crown","crude","cruel","crush",
"curve","cycle","daily","dairy","dance","dated","death","debut","debug","delay",
"delta","depth","dirty","dodge","doing","donut","doubt","dozen","draft","drain",
"drama","drawn","dream","dress","drift","drink","drive","drown","eager","early",
"earth","easel","edged","elder","elect","elite","empty","enemy","enjoy","enter",
"equal","equip","error","essay","ethic","evade","event","exact","exist","extra",
"faith","false","fancy","fatal","fault","feast","fence","fever","field","fiery",
"fight","final","first","flame","flash","fleet","flesh","float","flood","floor",
"fluid","focus","force","forum","found","frame","fresh","front","frost","fruit",
"giant","glide","globe","grace","grade","grain","grant","grape","graph","grasp",
"green","grind","group","guard","guess","guest","guide","habit","happy","harsh",
"heart","heavy","honey","honor","horse","hotel","house","human","humor","ideal",
"image","index","inner","input","issue","ivory","jelly","joint","judge","juice",
"knife","knock","label","labor","layer","learn","leave","lemon","level","light",
"limit","local","logic","loose","lucky","lunch","magic","major","maker","march",
"match","maybe","medal","metal","meter","might","minor","model","money","month",
"moral","motor","mount","mouse","mouth","movie","music","naive","nerve","never",
"night","noise","north","novel","nurse","occur","ocean","offer","often","onion",
"order","other","outer","owner","panel","panic","paper","party","peace","phase",
"phone","photo","piece","pilot","pitch","place","plain","plane","plant","plate",
"point","power","press","price","pride","prime","print","prior","prize","proof",
"proud","queen","quick","quiet","radio","raise","range","rapid","ratio","reach",
"react","ready","realm","rebel","refer","relax","renew","reply","right","rival",
"river","rough","round","route","royal","rugby","rural","scale","scene","scope",
"score","sense","serve","seven","shade","shake","shall","shape","share","sharp"
);


WORDS.push(
"shelf","shell","shift","shine","shirt","shock","shoot","shore","short","sight",
"since","skill","sleep","slice","slide","slope","small","smart","smile","smoke",
"solid","solve","sorry","sound","south","space","spade","spare","spark","speak",
"speed","spend","spice","spike","spill","spine","spite","split","spoil","spoke",
"sport","staff","stage","stand","start","state","steam","steel","stick","still",
"stock","stone","storm","story","strip","stuck","study","stuff","style","sugar",
"super","sweet","table","taste","teach","teeth","thank","their","theme","there",
"thick","thing","think","third","those","three","throw","tight","timer","tired",
"title","today","topic","total","touch","tough","tower","toxic","trace","track",
"trade","trail","train","treat","trend","trial","trick","trust","truth","twice",
"uncle","under","union","unity","until","upper","upset","urban","usage","usual",
"value","video","virus","visit","vital","vivid","vocal","voice","waste","watch",
"water","weary","weigh","whale","wheat","wheel","where","which","while","white",
"whole","woman","world","worry","worth","wound","write","wrong","yield","young",
"youth","zebra","abhor","abide","abled","abode","abuse","ached","aches","acids",
"acorn","acres","acted","adder","addle","adieu","adore","adorn","aegis","aerie",
"affix","afire","afoot","afoul","agape","agate","aglow","agony","agree","ahead",
"aided","aimed","aisle","alarm","album","alder","alert","alfal","align","alike",
"alive","allay","alley","allot","allow","alloy","aloft","alone","along","aloof",
"alter","amaze","amber","amend","amiss","among","ample","amply","amuse","angel",
"anger","angle","angry","anime","ankle","annex","annoy","antic","anvil","aorta",
"apart","aphid","apple","apply","apron","arena","argue","arise","armed","armor",
"aroma","array","arrow","ashen","aside","asset","atlas","atoll","attic","audio",
"audit","avail","avert","avoid","await","awake","award","aware","awful","axial",
"axiom","azure","bacon","badge","badly","bagel","baked","baker","baler","banal",
"bands","banjo","barge","basic","basil","beach","beads","beady","beard","beast",
"beats","began","begin","begun","being","belch","belly","below","bench","berth",
"berry","birth","black","blade","blame","blank","blast","blend","bless","blind",
"blink","block","blood","bloom","blown","blues","bluff","board","boast","bonus",
"boost","booth","borne","bound","brain","brake","brand","brave","bread","break",
"brick","bride","bring","broad","broke","brown","brush","build","built","burst",
"buyer","cabin","cable","camel","canal","candy","canny","canoe","cargo","carry",
"carve","catch","cause","chain","chair","chalk","champ","chant","chaos","charm",
"chart","chase","cheap","check","cheek","cheer","chess","chest","chief","child",
"chill","china","choir","choke","chord","cigar","cinch","claim","clash","class",
"clean","clear","clerk","click","cliff","climb","cling","clock","close","cloth",
"cloud","coach","coast","colon","color","comic","could","count","court","cover",
"craft","crane","crash","cream","creed","crime","cross","crowd","crown","crude",
"cruel","crush","curve","cycle","daily","dairy","dance","dated","death","debut",
"debug","delay","delta","depth","dirty","dodge","doing","donut","doubt","dozen",
"draft","drain","drama","drawn","dream","dress","drift","drink","drive","drown",
"eager","early","earth","easel","edged","elder","elect","elite","empty","enemy",
"enjoy","enter","equal","equip","error","essay","ethic","evade","event","exact",
"exist","extra","faith","false","fancy","fatal","fault","feast","fence","fever"
);

WORDS.push(
"feign","fetal","fetch","fiber","fifth","fifty","filly","filmy","filth","finer",
"first","fixed","flair","flake","flank","flare","flash","fleet","flick","fling",
"float","flock","flood","flora","flour","fluid","focus","force","forge","forth",
"forty","forum","found","frail","frame","frank","fraud","fresh","fried","front",
"frost","frown","fruit","gamer","gamma","gauge","genoa","genre","ghost","giant",
"giddy","given","glade","gland","glare","glass","glide","globe","glory","glove",
"grace","grade","grain","grand","grant","grape","graph","grasp","grass","grave",
"great","green","greet","grief","grind","groan","group","grove","grown","guard",
"guess","guest","guide","guild","habit","hairy","halve","handy","happy","hardy",
"hasty","haunt","heart","hedge","hefty","hello","hence","hobby","hoist","honor",
"horde","hotel","house","human","humid","humor","ideal","idiom","image","imply",
"inbox","index","infer","inner","input","irony","issue","ivory","jelly","joint",
"judge","juice","kneel","knife","knock","known","label","labor","lapse","large",
"laser","later","laugh","layer","learn","lease","least","leave","legal","lemon",
"level","light","limit","linen","liver","local","logic","loose","lower","lucky",
"lunar","lunch","magic","major","maker","mango","march","match","maybe","medal",
"media","mercy","merge","merit","metal","meter","might","minor","model","money",
"month","moral","motor","mount","mouse","mouth","movie","music","naive","nerve",
"never","niche","night","noise","north","novel","nurse","occur","ocean","offer",
"often","olive","onion","order","other","outer","owner","panel","panic","paper",
"party","pause","peace","phase","phone","photo","piece","pilot","pitch","place",
"plain","plane","plant","plate","point","power","press","price","pride","prime",
"print","prior","prize","proof","proud","queen","quick","quiet","radio","raise",
"range","rapid","ratio","reach","react","ready","realm","rebel","refer","relax",
"renew","reply","right","rival","river","rough","round","route","royal","rural",
"scale","scene","scope","score","sense","serve","seven","shade","shake","shall",
"shape","share","sharp","sheep","sheet","shelf","shell","shift","shine","shirt",
"shock","shoot","shore","short","sight","since","skill","sleep","slice","slide",
"slope","small","smart","smile","smoke","solid","solve","sorry","sound","south",
"space","spare","speak","speed","spend","spice","spike","spine","spite","split",
"sport","staff","stage","stand","start","state","steam","steel","stick","still",
"stock","stone","storm","story","strip","study","stuff","style","sugar","super",
"sweet","table","taste","teach","thank","their","theme","there","thick","thing",
"think","third","those","throw","tight","timer","tired","title","today","topic",
"total","touch","tower","toxic","trace","track","trade","train","treat","trend",
"trial","trust","truth","twice","uncle","under","union","unity","until","upper",
"upset","urban","usage","usual","value","video","virus","visit","vital","vivid",
"voice","waste","watch","water","weigh","whale","wheat","wheel","where","which",
"while","white","whole","woman","world","worry","worth","write","wrong","yield",
"young","youth"
);

WORDS.push(
"abbot","abuzz","afore","ahold","alums","amity","annal","anted","aptly","arbor",
"ardor","avail","bared","baser","bawdy","beget","billy","birch","bison","blare",
"bleak","blimp","brawl","briar","broil","bulky","caper","chide","clang","clasp",
"cower","covet","crept","cubic","dally","decry","deter","dinky","dirge","diver",
"dowry","duchy","dusky","elate","ember","ensue","epoch","erupt","evoke","fable",
"facet","feral","ferry","finer","fjord","forgo","friar","fungi","gaily","girth",
"gloom","gnash","gourd","hatch","havoc","hilly","hippo","homer","icily","inert",
"jaded","jaunt","jazzy","khaki","kiosk","latch","leafy","libel","livid","loamy",
"lunge","madly","mirth","mossy","nanny","nasal","niece","nymph","omega","ovate",
"pagan","petal","plaid","pluck","quack","quart","rabid","raven","reedy","risky",
"rivet","sassy","scowl","sever","shady","skirt","slack","sneak","soggy","swoop",
"tempo","thyme","tulip","ulcer","vigor","waist","warty","whiff","wiser","xerox",
"yeast","zesty"
);
WORDS.push(
"abide","abode","abort","acrid","adept","adorn","afoot","afoul","aglow","agora",
"aisle","alert","algae","alloy","aloft","amity","anode","anted","antic","anode",
"aping","apnea","aptly","arced","ardor","argot","arson","ascot","ashen","atone",
"attic","augur","avail","avert","axion","azure","baler","balmy","banjo","baron",
"baste","bayed","beech","befit","begat","beget","beryl","beset","betel","bevel",
"binge","biome","bison","bland","blare","bleat","bleed","bleep","blimp","bliss",
"bloat","boney","borax","borne","bosom","brace","braid","brawn","briar","briny",
"brisk","broil","broom","brunt","bused","cairn","canid","caput","caret","cargo",
"carol","caste","caulk","cedar","chafe","chard","chide","chime","chirp","chive",
"civet","clack","clang","clank","clasp","cleat","cleft","clime","clink","clout",
"cobra","comet","conch","copse","coral","corny","cower","coyly","cramp","crank",
"creak","crept","crock","crony","crumb","cumin","curio","curly","curry","curse",
"cutie","cyber","dally","debar","decry","defer","deign","deity","delta","demon",
"demur","denim","deter","dilly","dimer","diner","dirge","disco","ditto","diver",
"dizzy","dodge","dogma","dolly","donor","douse","dowry","drape","dread","drier",
"droll","druid","dryer","duchy","dully","dusky","dwarf","dwell","eclat","edict",
"egret","elate","elide","elope","elude","ember","emcee","emery","emote","ensue",
"epoch","epoxy","equip","erode","erupt","essay","ester","ether","ethos","etude",
"evoke","exact","exalt","excel","exert","exile","expel","extol","extra"
);


WORDS.push(
"fable","facet","faint","fairy","faith","fancy","fanny","farce","fatal","fatty",
"feast","fecal","feign","fella","felon","femur","ferry","fetal","fetch","fetus",
"fiber","fibre","ficus","fifth","fifty","filly","filmy","filth","final","finch",
"finer","first","fishy","fixer","fizzy","fjord","flack","flake","flaky","flank",
"flare","flash","flask","fleck","fleet","flesh","flick","flier","fling","flint",
"float","flock","flood","flora","floss","flour","flout","flown","fluff","fluid",
"fluke","flume","flung","flush","flute","foamy","focal","focus","foggy","foist",
"folio","folly","foray","force","forge","forgo","forte","forth","forty","forum",
"found","frail","frame","frank","fraud","freak","freed","freer","fresh","fried",
"frill","frisk","frock","frond","front","frost","froth","frown","fruit","fudge",
"fugue","fully","fungi","funky","funny","furor","furry","fussy"
);
WORDS.push(
"aback","abaft","abase","abate","abbey","abbot","abhor","abide","abled","abode",
"abort","abuzz","ached","aches","acorn","acrid","actor","acute","adage","adapt",
"addle","adept","adieu","adorn","aegis","aerie","affix","afire","afoot","afoul",
"agape","agate","agave","agent","agile","aging","aglow","agony","agree","ahead",
"aisle","alamo","alder","aleph","allay","alley","allot","alloy","aloft","altar",
"amber","amend","amiss","amply","amuse","anode","anted","antic","anvil","aorta",
"apart","aphid","aping","apnea","aptly","arbor","ardor","argot","arson","ascot",
"ashen","atoll","attic","augur","aural","avail","avert","axial","axiom","azure"
);
WORDS.push(
"admit","adopt","agree","allow","amend","apply","argue","arise","avoid","await",
"begin","blame","blend","bless","blind","boost","break","bring","build","burst",
"carry","catch","cause","chase","check","cheer","choke","claim","clean","clear",
"climb","close","count","cover","craft","crash","crawl","creep","drink","drive",
"drown","enjoy","enter","equip","evade","exist","fight","focus","force","forgo",
"forge","frame","grasp","guard","guess","guide","learn","leave","level","limit",
"march","match","offer","order","paint","phase","place","plant","press","prove",
"raise","reach","react","refer","relax","renew","reply","serve","shape","share",
"shift","shoot","solve","spare","speak","spend","split","stand","start","stick",
"study","teach","thank","think","throw","touch","trace","track","trade","train",
"treat","trust","visit","watch","write"
);
WORDS.push(
"acorn","amber","angel","ankle","apple","arena","armor","arrow","atlas","audio",
"badge","basil","beach","beard","bench","berry","birth","blade","board","brain",
"bread","brick","brush","cabin","cable","camel","candy","cargo","chain","chair",
"chalk","charm","chess","chest","child","choir","cigar","clock","cloud","coach",
"coast","color","court","crown","cycle","dance","death","delta","dream","dress",
"earth","easel","elder","enemy","essay","event","faith","fence","field","flame",
"flood","floor","focus","frame","fruit","ghost","globe","grace","grain","grape",
"graph","grass","green","group","guard","guest","guide","habit","heart","honey",
"horse","hotel","house","human","image","index","issue","jelly","joint","judge",
"knife","label","layer","lemon","level","light","lunch","magic","major","medal",
"metal","meter","model","money","month","motor","mount","mouse","mouth","movie",
"music","nerve","night","noise","north","novel","nurse","ocean","offer","onion",
"order","owner","panel","paper","party","peace","phase","phone","photo","piece",
"pilot","pitch","place","plane","plant","plate","point","power","price","prize",
"queen","radio","range","ratio","realm","river","route","scale","scene","scope",
"score","sense","shade","shape","share","sheet","shell","shirt","shock","shore",
"sight","skill","sleep","slice","smile","smoke","sound","space","spice","spite",
"sport","stage","state","steam","steel","stone","storm","story","style","sugar",
"sweet","table","taste","theme","thing","title","topic","tower","trace","track",
"trade","trial","truth","uncle","union","unity","value","video","voice","waste",
"water","wheel","white","whole","woman","world","youth"
);

WORDS.push(
"absey","abyss","azoth","baize","buxom","cairn","civet","cloze","coyly","croon",
"crypt","cumin","curio","duvet","dweeb","eclat","egret","embay","emcee","enoki",
"ensky","epact","ester","ether","ethos","etude","exalt","exile","expel","extol",
"fjord","flume","flung","foamy","folio","foray","friar","fugal","fungi","furor",
"gaily","gamut","gauze","gawky","gipsy","gnash","gnome","gourd","grail","groan",
"gruel","guano","haiku","harem","haunt","hilly","homer","hyena","ibexx","icing",
"ionic","irate","ivied","jaded","jaunt","jazzy","jerky","joust","khaki","kiosk",
"llama","loamy","lupus","lymph","mangy","mirth","mossy","myrrh","nymph","ovate",
"oxide","ozone","pagan","quack","quart","quell","query","quill","quilt","rabid",
"raven","reedy","rivet","sassy","scowl","serif","shady","skulk","slack","slyly",
"soggy","sough","swoop","tempo","thyme","ulcer","umbra","vigor","vixen","waist",
"waltz","warty","whiff","wimpy","xerox","yacht","yeast","zesty","zonal"
);

WORDS.push(
"abbes","abbey","abbot","abeam","abele","abler","ables","abmho","abode","abohm",
"aboil","aboon","abord","abore","abort","about","above","absit","abuna","abune",
"abuse","abuts","abuzz","abyss","acari","accoy","acerb","aceta","achar","ached",
"acher","aches","achoo","acids","acing","acini","ackee","acker","acmes","acmic",
"acned","acnes","acock","acold","acorn","acred","acres","acrid","acros","acted",
"actin","acton","actor","acute","acyls","adage","adapt","added","adder","addle",
"adeem","adept","adhan","adieu","adios","adits","adman","admen","admin","admit",
"admix","adobe","adobo","adopt","adore","adorn","adown","adoze","adult","adunc",
"adust","advew","adyta","adzed","adzes","aecia","aedes","aegis","aeons","aerie"
);
WORDS.push(
"afars","afear","affix","afire","afoot","afore","afoul","afrit","afros","agama",
"agami","agape","agars","agast","agate","agave","agent","agers","agger","aggie",
"aggri","aggro","aghas","agile","aging","agios","agism","agist","agita","aglee",
"aglet","agley","aglow","agmas","agoge","agone","agons","agony","agood","agora",
"agree","agria","agrin","agros","ahead","aheap","ahent","ahigh","ahind","ahing",
"ahint","ahold","ahull","ahuru","aided","aides","aidoi","aidos","aiery","aigas",
"ailed","aimed","aimer","ainee","ainga","aioli","aired","airer","airns","airth"
);
WORDS.push(
"ajarz","ajies","ajiva","ajuga","ajwan","akees","akela","akene","aking","akita",
"akkas","alaap","alack","alamo","aland","alane","alang","alans","alant","alapa",
"alaps","alarm","alary","alate","alays","albas","albee","album","alcid","alcos",
"aldea","alder","aldol","aleck","alecs","aleft","aleph","alert","alews","aleye",
"alfas","algal","algas","algid","algin","algor","algum","alias","alibi","alien",
"alifs","align","alike","aline","alios","alist","alive","aliya","alkie","alkos",
"alkyd","alkyl","allay","allee","allel","alley","allis","allod","allot","allow"
);
WORDS.push(
"again","along","always","angry","asked","baker","beach","begin","black","bring",
"build","buyer","cause","cheap","clean","clear","climb","clock","close","count",
"daily","dance","doing","dream","drink","drive","earth","eight","enjoy","field",
"fight","final","floor","found","fresh","front","funny","glass","going","great",
"green","group","happy","heard","heart","heavy","hello","house","human","image",
"inside","issue","large","learn","leave","light","lived","local","loved","lucky",
"maybe","money","month","morning","mouth","music","never","night","north","often",
"order","other","paper","party","peace","phone","place","plant","point","power",
"quick","quite","radio","ready","right","round","school","score","sense","serve",
"seven","short","since","small","sound","south","space","start","state","still",
"story","study","table","taken","taste","teach","their","there","these","thing",
"think","three","today","topic","total","touch","train","under","until","value",
"video","voice","water","where","which","while","white","whole","woman","world",
"write","wrong","young"
);
WORDS.push(
"abide","abode","adorn","aglow","amity","anode","aping","arbor","ardor","argot",
"ascot","atone","augur","aural","bairn","balmy","bated","bawdy","bezel","bicep",
"boney","bosom","briar","briny","brisk","broom","brunt","cairn","canid","caput",
"cavil","chafe","chard","chime","chirp","chive","civet","clank","cleft","clime",
"clink","clout","cobra","comet","conch","copse","coral","corny","covey","coyly",
"crank","creak","crept","crock","crony","crumb","cumin","curio","curly","curry",
"cutie","dally","debar","decry","defer","deign","demur","denim","deter","dimer",
"diner","dizzy","dogma","dolly","donor","douse","dread","drier","droll","druid",
"dryer","dully","dwell","edict","egret","elide","elope","elude","emote","epoxy",
"erode","ester","ether","ethos","etude","exalt","exert","exile","expel","extol",
"fable","facet","faint","fairy","farce","fecal","felon","femur","fetus","ficus",
"fixer","fjord","flack","flaky","flask","fleck","flier","flint","floss","flout",
"fluke","flume","foamy","folio","foray","forte","frail","freak","friar","froth",
"fugue","fungi","gaily","girth","glade","gland","glory","gnash","gnome","gourd",
"grail","gruel","guano","haiku","harem","hedge","hoard","homer","hyena","icily",
"idiom","imply","inert","irony","ivied","jaunt","jazzy","joust","khaki","kiosk",
"lapse","latch","leafy","libel","livid","loamy","lunge","mirth","mossy","nymph",
"omega","ovate","pagan","petal","plaid","pluck","quack","quart","rabid","raven",
"reedy","rivet","sassy","scowl","serif","skulk","slyly","soggy","sough","swoop",
"tempo","thyme","umbra","vigor","vixen","waist","waltz","warty","whiff","wimpy",
"xerox","yeast","zesty","zonal"
);
WORDS.push(
"about","above","after","apple","award","basic","below","brown","chair","child",
"class","color","court","cover","death","early","error","event","faith","force",
"frame","front","fruit","ghost","grace","grade","grand","grass","green","guide",
"hotel","house","index","joint","judge","knife","known","label","laugh","layer",
"level","magic","major","match","metal","model","motor","movie","north","ocean",
"offer","owner","panel","phase","piece","pilot","pitch","plain","plane","plate",
"price","pride","print","prize","queen","radio","range","river","rough","royal",
"rural","scale","scene","scope","sheet","shell","shirt","shock","shoot","shore",
"sight","skill","sleep","slice","smile","smoke","solid","solve","sorry","speak",
"spend","spice","split","sport","staff","stage","steam","steel","stone","storm",
"style","sugar","sweet","table","theme","thick","thing","throw","tight","title",
"tower","trace","track","trade","treat","trial","trust","truth","twice","uncle",
"union","unity","upper","usual","visit","vital","waste","watch","wheel","worth",
"yield","youth"
);
WORDS.push(
"about","above","after","again","apple","apply","awake","award","basic","beach",
"begin","black","blame","block","blood","board","brain","bread","break","bring",
"brown","build","cause","chain","chair","chart","check","clean","clear","clock",
"close","coach","could","count","court","cover","craft","cream","dance","death",
"dream","dress","drink","drive","early","earth","enemy","enter","equal","event",
"faith","field","fight","final","first","floor","force","found","frame","front",
"fruit","green","group","guard","guess","happy","heart","heavy","house","human",
"image","index","input","issue","judge","knife","label","learn","leave","level",
"light","limit","local","logic","lucky","lunch","magic","major","march","match",
"maybe","metal","money","month","moral","motor","mount","mouse","mouth","music",
"never","night","noise","north","novel","ocean","offer","often","order","other",
"owner","paper","party","peace","phase","phone","photo","piece","place","plane",
"plant","plate","point","power","press","price","pride","prime","print","prior",
"queen","quick","quiet","radio","raise","range","reach","ready","right","river",
"round","route","royal","scale","scene","score","sense","serve","seven","share",
"sharp","sheet","shelf","shell","shift","shine","shirt","short","sight","since",
"skill","sleep","small","smart","smile","sound","south","space","spare","speak",
"speed","spend","sport","stage","stand","start","state","steam","stone","story",
"study","stuff","style","sugar","sweet","table","teach","thank","their","theme",
"there","thick","thing","think","third","those","throw","tight","tired","title",
"today","total","touch","tower","trace","track","trade","train","treat","trend",
"trial","trust","truth","twice","under","union","until","upper","usage","value",
"video","visit","vital","voice","waste","watch","water","wheel","where","which",
"while","white","whole","woman","world","worry","worth","write","wrong","young"
);


WORDS.push(
"areas","arms","asks","atoms","backs","balls","bands","banks","bases","bears",
"beats","beds","bells","belts","bends","bills","birds","bitsy","boats","bonds",
"bones","books","boots","boys","brass","bricks","briefs","brims","brings","builds",
"calls","calms","camps","cards","cares","carts","cases","casts","cells","chats",
"chefs","chips","chores","cites","class","claps","claws","clays","clips","clots",
"clubs","coats","coins","comes","cooks","cools","costs","crops","crowds","cups",
"darts","dates","dayss","deals","dears","debts","decks","deeds","diets","dimes",
"disks","doors","downs","draws","drops","drums","ducks","duels","duets","dukes",
"earns","ears","edges","elves","emails","ends","faces","facts","fails","falls",
"farms","fears","feeds","feels","fells","fields","files","fills","films","fires",
"firms","flags","flats","fleas","flies","floats","floods","floors","flows","foams",
"foods","fools","forms","forts","fours","frames","fries","frogs","funds","gains",
"games","gases","gates","gears","gifts","girls","gives","glads","goals","goats",
"grabs","grades","grains","grants","grapes","graphs","grays","greens","grills","grips",
"groups","guards","guests","guides","habits","hands","hangs","heads","heals","hears",
"heats","helps","hills","hints","holds","holes","homes","hopes","hours","ideas",
"items","jokes","jumps","keeps","kicks","kills","kinds","kings","knots","lacks",
"lands","lanes","lasts","leads","leaks","leans","leaps","leaves","legs","lends",
"lifts","lights","likes","lines","links","lists","lives","loads","loans","locks",
"logs","looks","loops","loses","loves","mails","makes","marks","masks","meals",
"means","meets","mends","miles","minds","mines","misss","modes","moons","moves",
"names","needs","nests","nets","news","notes","nouns","nurses","oaths","odors",
"offers","opens","orders","pages","pairs","pants","parks","parts","paths","peaks",
"pears","peeks","peers","pens","pets","picks","piles","plans","plays","plots",
"points","polls","pools","ports","posts","press","price","pride","primes","prints",
"prizes","prods","props","pulls","pushs","quits","races","rails","rains","ranks",
"rates","reads","rests","rides","rings","risks","rivers","roads","rocks","rolls",
"rooms","roots","ropes","rules","runs","sails","sales","sands","saves","seals",
"seams","sears","seats","seeds","seeks","seems","sells","sends","septs","sets",
"shaps","shares","shifts","ships","shirts","shoes","shoots","shops","shots","shows",
"sides","signs","skills","skins","slaps","sleeps","slides","slips","slots","slows",
"smalls","smells","smiles","smokes","snaps","sneaks","snows","soaps","socks","songs",
"sorts","souls","sounds","soups","spaces","spans","speaks","speeds","spells","spends",
"spins","spits","spots","sprays","squats","staffs","stags","stains","stamps","stands",
"stars","stays","steals","steams","steps","sticks","stills","stocks","stones","stops",
"stores","storms","stoves","straps","straws","strips","studs","styles","sucks","suits",
"superb","swaps","sways","swims","swings","swords","tables","takes","talks","tanks",
"tapes","tasks","teams","tears","teens","tells","tends","terms","tests","texts",
"thats","themes","things","thinks","thirds","those","throws","times","tireds","titles",
"tolls","tools","tops","tours","towers","towns","tracks","trades","trails","trains",
"treats","trends","tricks","trips","trusts","truths","turns","types","units","uses",
"values","views","visits","votes","waits","walks","walls","wants","wards","warns",
"wastes","waves","wears","weeks","wells","wests","whats","wheels","whites","winds",
"wings","wipes","wires","wises","words","works","worlds","wounds","writes","years",
"yells","yours"
);




WORDS.push(
"joker","poker","entry","goast","hours","yours","minds","retry","cruck","smash","slash","noobs","trash","ajest","rises"
);


// --- 5文字以外を自動削除 + 小文字統一 + 重複削除 ---
WORDS = [...new Set(
  WORDS
    .map(w => w.toLowerCase().trim())
    .filter(w => /^[a-z]{5}$/.test(w))
)];

// ===== FINAL: 重複除去 + シャッフル + 最終辞書出力 =====

// 小文字化して5文字のみ念のため保証
const cleaned = WORDS
  .map(w => w.toLowerCase())
  .filter(w => w.length === 5);

// 重複完全除去
const unique = [...new Set(cleaned)];

/* Fisher–Yates シャッフル
for (let i = unique.length - 1; i > 0; i--) {
  const j = Math.floor(Math.random() * (i + 1));
  [unique[i], unique[j]] = [unique[j], unique[i]];
}
*/

function shuffle(array) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
  return array;
}

// 例
shuffle(WORDS);


// コピペ用に出力
const output =
  "const WORDS = [\n" +
  unique.map(w => `"${w}"`).join(",") +
  "\n];";

console.log(output);
